name: 1429
on:
  issues:
    types: [opened]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: env
      - run: ls
      - run: cat ${{ github.event }}
      - run: cat ${{ github.event_path }}      