name: 1429
on:
  issues:
    types: [opened]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: env
      - run: ls
      - run: echo ${{ github.event }}
      - run: cat /home/runner/work/_temp/_github_workflow/event.json    